version: 2.1

jobs:
    test-021: &test-job
        environment:
            SKLEARN_VERSION: 0.21.3
        docker:
            - image: circleci/python:3.7.3
        steps:
            - checkout
            - run: pip install --user pytest scikit-learn==$SKLEARN_VERSION
            - run: python test.py

    test-022:
        <<: *test-job
        environment:
            SKLEARN_VERSION: 0.22.2.post1

    test-022-limited-threads:
        <<: *test-job
        environment:
            SKLEARN_VERSION: 0.22.2.post1
            OMP_NUM_THREADS: 1

workflows:
    test:
        jobs:
            - test-021
            - test-022
            - test-022-limited-threads
